[template]
cargo_generate_version = ">=0.10"

[placeholders.contract-name]
type = "string"
prompt = "What is the name of your main contract?"
regex = "^[a-z][a-z0-9_]*$"

[placeholders.author]
type = "string"
prompt = "Author name (for GitHub URL)"
default = "your-username"

